### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by MrWZZ** [Vhati/Slipstream-Mod-Manager#10]
00:00:04.737 [Thread-15] ERROR net.vhati.modmanager.core.ModPatchThread - Patching failed. java.nio.charset.UnmappableCharacterException: Input length = 1
	at java.nio.charset.CoderResult.throwException(Unknown Source)
	at sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
	at sun.nio.cs.StreamEncoder.write(Unknown Source)
	at java.io.OutputStreamWriter.write(Unknown Source)
	at net.vhati.modmanager.core.EOLWriter.write(EOLWriter.java:75)
	at net.vhati.modmanager.core.EOLWriter.write(EOLWriter.java:81)
	at java.io.Writer.write(Unknown Source)
	at org.jdom2.output.support.AbstractXMLOutputProcessor.write(AbstractXMLOutputProcessor.java:342)
	at org.jdom2.output.support.AbstractXMLOutputProcessor.printComment(AbstractXMLOutputProcessor.java:711)
	at org.jdom2.output.support.AbstractXMLOutputProcessor.printContent(AbstractXMLOutputProcessor.java:940)
	at net.vhati.modmanager.core.SloppyXMLOutputProcessor.printElement(SloppyXMLOutputProcessor.java:113)
	at org.jdom2.output.support.AbstractXMLOutputProcessor.printDocument(AbstractXMLOutputProcessor.java:533)
	at org.jdom2.output.support.AbstractXMLOutputProcessor.process(AbstractXMLOutputProcessor.java:191)
	at org.jdom2.output.XMLOutputter.output(XMLOutputter.java:822)
	at net.vhati.modmanager.core.SloppyXMLOutputProcessor.sloppyPrint(SloppyXMLOutputProcessor.java:165)
	at net.vhati.modmanager.core.ModUtilities.patchXMLFile(ModUtilities.java:257)
	at net.vhati.modmanager.core.ModPatchThread.patch(ModPatchThread.java:242)
	at net.vhati.modmanager.core.ModPatchThread.run(ModPatchThread.java:88)

**Comment by Vhati** [comment]
UnmappableCharacterException happens when patching FTL 1.01-1.5.13 if a mod contains an unusual character that the game wouldn't display correctly - had patching been allowed to finish.

Selecting a mod and clicking the "Validate" button should identify any problematic characters for the mod developer to remove.

FTL 1.6.1+ is less picky about characters, so Slipstream won't throw an error in that case. It's possible that mods intended for - or only tested with - FTL 1.6.1+ may incidentally have a character that breaks backwards compatibility with the older editions.

Either way the dev should be notified.

**Comment by Eboubaker** [comment]
same issue when trying to install multiverse mod
